- name: Configure cart
  hosts: cart
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system cart roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system cart"
  
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent  # Delete /app directory

  - name: create app directory
    ansible.builtin.file: # To create dir
      path: /app
      state: directory

  - name: delete cart zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: download cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: unarchive cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app

  - name: copy cart service
    ansible.builtin.template:  # --> this will replace with the variables, don't use copy module
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload  # bcz ? above did changes in service file so...
    ansible.builtin.systemd_service: 
      daemon_reload: true

  - name: start cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes
      