- name: Configure Catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs 20 # Used command module because dnf module not support module enable
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent  # Delete /app directory

  - name: create app directory
    ansible.builtin.file: # To create dir
      path: /app
      state: directory

  - name: delete catalogue zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download catalouge code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip

  - name: unarchive catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue service
    ansible.builtin.template: # To copy file from local to remote substitute variables
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded # used command module
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  # - name: print output
  #   ansible.builtin.debug:
  #     msg: "{{ catalogue_output }}"

  - name: load the products  # Here shell module used
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0 # converting string to int (stdout is string)
    # Then load the products data to mongodb

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes
      