- name: create EC2 and Route53 records
  hosts: all  # TO run :: ansible-playbook -i localhost, create-ec2.yaml
  connection: local
  vars:
    sg_id: sg-04303efbdaed5c6f9
    ami_id: ami-0220d79f3f480ecf5
    domain_name: dawsmani.site
    env: dev
    action: create
    instances: # List 
    - mongodb
    - catalogue
  tasks:
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:  
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}" # To display Instance name at instances UI
    loop: "{{ instances }}"  # 1st time mongodb comes here
    register: ec2_output
    when: action == "create"

  - name: print output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
    when: action == "create"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # mongodb-dev.dawsmani.site, frontend-dev.dawsmani.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"  # 1st Instance index is 0
      wait: true
    loop: "{{ ec2_output.results }}"
    # when: action == "create"

  - name: create r53 public record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" # roboshop-dev.dawsmani.site
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"  # 1st Instance index is 0
      wait: true
    loop: "{{ ec2_output.results }}"
    when: item.item == "frontend"