- name: create EC2 and Route53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-04303efbdaed5c6f9
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instances: # List 
    - mongodb
    - catalogue
  tasks:
  - name: create EC2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:  
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}" # To display Instance name at instances UI
    loop: "{{ instances }}"  # 1st time mongodb comes here
    register: ec2_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"