- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Remove the default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: download frontend
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /tmp/frontend.zip

  - name: Extract the frontend content.
    ansible.builtin.command:
    args:
      chdir: 

  - name: unarchieve frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy frontend service
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf # To copy file from local to remote substitute variables

  - name: start enable nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: true