- name: configure frontend server
  hosts: frontend
  become: yes

  tasks:

    - name: Enable nginx 1.24 module
      ansible.builtin.dnf:
        name: '@nginx:1.24'
        state: present

    - name: Install unzip
      ansible.builtin.dnf:
        name: unzip
        state: present

    - name: Remove default nginx html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Recreate html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Download frontend
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: Unarchive frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy nginx configuration
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted