- name: Configure user
  hosts: user
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent  # Delete /app directory

  - name: create app directory
    ansible.builtin.file: # To create dir
      path: /app
      state: directory

  - name: delete user zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unarchive user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app

  - name: copy user service
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon-reload # bcz ? above did changes in service file so...
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
      
      